spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    static-path-pattern: /resources/**
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/crawler
    username: spring
    password: spring
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

application:
  file-loader:
    api-model:
      path: /home/malachai/Workspace/projects/finance-dashboard/conf/api.json