spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    static-path-pattern: /resources/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crawler
    username: spring
    password: spring
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true